version: '3.7'

services:

# docker run -d --rm -p 5432:5432 -e POSTGRES_PASSWORD=asd -e POSTGRES_USER=postgres db

  db:
    build: ./db
    restart: always
    ports:
      #- 5432:5432
      - 5432:5432
    env_file:
      - "db/database.env"
    #volumes:
    #  -
    #    type: bind
    #    source: /tmp/postgres-data
    #    target: /var/lib/postgresql/data
    networks: 
      app_network:
        aliases: 
          - db_host
      
  
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - "api/api.env"
    depends_on:
      - db
    restart: unless-stopped
    networks: 
      app_network:
        aliases: 
          - api_host

  nuxt:
    build:
      context: ./webpage
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev -- -p 3001
    volumes:
    - .:/code
    - /code/node_modules
    ports:
      - "3001:3001"
    networks: 
      app_network:
        aliases: 
          - nuxt_host

  nuxt2:
    build:
      context: ./webpage2
    image: nuxt_dev2
    container_name: nuxt_dev2
    command: npm run dev -- -p 3002
    volumes:
    - .:/code
    - /code/node_modules
    ports:
      - "3002:3002"
    networks: 
      app_network:
        aliases: 
          - nuxt2_host

  nginx:
      build: ./nginx
      ports:
        - 8080:80
      depends_on:
        - nuxt
        - nuxt2
    
 # app:
 #   build: ./cleverhome_frontend 
 #   ports:
 #     - 80:80
 #   depends_on:
 #     - api
 #   networks: 
 #     app_network:
 #       aliases: 
 #         - app_host
    

networks: 
  app_network:
    name: appnet
    driver: bridge
    ipam:
      driver: default
